---
apiVersion: cloudfoundry.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  namespace: default
spec:
  apiEndpoint: https://api.cf.eu12.hana.ondemand.com
  credentials:
    source: Secret
    secretRef:
      name: cf-credentials-secret
      namespace: default
      key: credentials